Fri Jan 5 10:06:12 IST 2024

SLURM_JOBID:		 1014196
SLURM_JOB_NODELIST:	 cs-pheno-12 


python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba2        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_0_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba5        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_1_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba4        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_2_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba1        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_3_23
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba5.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba4.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba5        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_4_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba3        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_5_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba4        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_6_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba3        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_7_23
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba5.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba4.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba1        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_8_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba6        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_9_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba4        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_10_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba6        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_11_23
Traceback (most recent call last):
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba6.npy'
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba6.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba4.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba2        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_12_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba3        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_13_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba2        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_14_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba1        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_15_23
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba6        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_16_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba1        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_17_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba5        --seed 11 --strains 1  --dense 0 --n 100 --intense -1 --CMDprogress_18_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba6        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_19_23
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba6.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba5.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba6.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba2        --seed 11 --strains 3  --dense 0 --n 100 --intense -1 --CMDprogress_20_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba5        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_21_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba3        --seed 11 --strains 2  --dense 0 --n 100 --intense -1 --CMDprogress_22_23
python run.py --epoches 150000 --modelLoad AA --weightModel identical --randomGraph ba4        --seed 11 --strains 4  --dense 0 --n 100 --intense -1 --CMDprogress_23_23
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba5.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 72, in <module>
    A, G= random_graph.read_from_file("graphs/"+paras.randomGraph+".npy")
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/random_graph.py", line 130, in read_from_file
    Anp= np.load(FileName)
  File "/home/lx/.conda/envs/tf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/ba4.npy'
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/run.py", line 224, in <module>
    utils.log_print(printFlag,"recall:", evaluate.recall(Awse, PreAse))
  File "/sise/home/lx/code/12_1_topology_learning/Topology_Learning_Epis/modules/evaluate.py", line 42, in recall
    Z= torch.tensor(continious_to_sparcity(Z.numpy(), links))+IMatrix
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
